### PR TITLE
fix(stream): resume connection when stream errors or is destroyed

### LINKED ISSUE #1168: Query streamed with .stream() does not close when the stream has an error
When streaming a query with pool.query.stream(), if .destroy() is called on the stream, the 'close' event does not propagate upstream and close the underlying connection, leaving dead connections in the pool which are still executing.

As such it seems best to forcibly close the connection as I do not think mysql has a way to cancel a query while leaving the connection open.

Please see quick fix below, I have not had time yet to write a test or to confirm that this is the proper way to close the connection, or whether it might have other side effects:
https://github.com/CloudQuote/node-mysql2/commit/ac9236c7638974c100c421a79ec516f5df3fa156

### LINKED ISSUE #1847: Connection errors are not propagated to the query stream
Sample code:
```js
import { createPool } from "mysql2";

const connection = createPool({
    host: 'localhost',
    user: 'user',
    password: 'pass',
  });
try {
  for await (const row of connection.query("SELECT * FROM big_table").stream()) {
    // handle row here
  }
} catch (e) {
  // connection errors are not caught here
  console.log('caught error', e);
}
```

If any connection errors occur during the command execution, they will not be caught while iterating over the rows.

After investigation I found the issue to be in `Connection.notifyError` here https://github.com/sidorares/node-mysql2/blob/88587c6b64e71a82ca004170eccda3fb1ce81ed1/lib/connection.js#L224-L230

From what I see, the error will be passed to the command only if the command was executed with a callback.

A solution that seems to fix the issue is to also emit the error to the command like this:
```js
if (this._command) {
  this._command.emit('error', err);
}
```

With the above change the error will be emitted to the command, and will also be thrown when iterating over the stream.

Can be reproduced by running a slow query like `SELECT SLEEP(30)` and then issue a `KILL "connection id"`

### LINKED ISSUE #3596: Streaming pipeline errors block connections
This issue was written for `mysql`, but the problem also exists in `mysql2`. The `mysql` repository no long accepts issues from non-contributors... The patch attached is for `mysql`, but I believe the same changes can be made to `query.js` in `mysql2`.

I'll look into making a PR with tests when I have the time.

---

Running this script will hang the process when `pool.end` is called:

<details><summary>test.mjs</summary>

```js
import { createPool } from 'mysql'; // mysql or mysql2
import { pipeline } from 'node:stream/promises';

const pool = createPool({
  host: process.env.MYSQL_HOST,
  port: Number(process.env.MYSQL_PORT),
  user: process.env.MYSQL_USER,
  password: process.env.MYSQL_PASSWORD,
  database: process.env.MYSQL_DATABASE,
  poolConnectionLimit: 1,
  multipleStatements: true,
});

const promisify = (fn) =>
  new Promise((resolve, reject) =>
    fn((exn, conn) => (exn ? reject(exn) : resolve(conn)))
  );

const conn = await promisify((cb) => pool.getConnection(cb));

try {
  const stream = conn.query('select 1; select sleep(1);').stream({});
  await pipeline(stream, async function* (source) {
    for await (const chunk of source) {
      console.log('chunk:', chunk);
      throw new Error();
    }
  }).catch((err) => console.log('caught:', err));
} finally {
  conn.release();
  console.log('released');
}

// also hangs here
// console.log(await promisify((cb) => conn.query('select 1', cb)));

await promisify((cb) => pool.end(cb));

console.log('done');
```

</details> 

This was noticed during test cleanup from `pool.end`, but it will also prevent additional queries after `release` is called.

The issue is that the connection gets paused, but is never resumed. This prevents the protocol sequence from ever processing `Quit` and the necessary callbacks from `end`.

Here is a yarn patch I've made for **mysql** to fix the problem:

<details><summary>Details</summary>

```diff
diff --git a/lib/protocol/sequences/Query.js b/lib/protocol/sequences/Query.js
index b7632959b6b18eff0a239456c67b2696a5b931bd..d085e63dde4d320ac34a2b39d74386f661f66e7a 100644
--- a/lib/protocol/sequences/Query.js
+++ b/lib/protocol/sequences/Query.js
@@ -190,37 +190,50 @@ Query.prototype._sendLocalDataFile = function(path) {
 };
 
 Query.prototype.stream = function(options) {
-  var self = this;
-
-  options = options || {};
-  options.objectMode = true;
-
-  var stream = new Readable(options);
-
-  stream._read = function() {
-    self._connection && self._connection.resume();
-  };
+  const self = this;
+  const stream = new Readable({
+    ...options,
+    objectMode: true,
+    destroy() {
+      // Must resume connection or else it will block
+      self._connection?.resume();
+
+      self.removeListener('result', on_result);
+      self.removeListener('error', on_error);
+      self.removeListener('end', on_end);
+      self.removeListener('fields', on_fields);
+
+      stream.removeListener('end', once_end);
+    },
+    read() {
+      self._connection?.resume();
+    },
+  });
 
-  stream.once('end', function() {
+  stream.once('end', function once_end() {
     process.nextTick(function () {
       stream.emit('close');
     });
   });
 
-  this.on('result', function(row, i) {
+  this.on('result', function on_result(row, i) {
+    if (stream.destroyed) return;
     if (!stream.push(row)) self._connection.pause();
     stream.emit('result', row, i);  // replicate old emitter
   });
 
-  this.on('error', function(err) {
+  this.on('error', function on_error(err) {
+    if (stream.destroyed) return;
     stream.emit('error', err);  // Pass on any errors
   });
 
-  this.on('end', function() {
+  this.on('end', function on_end() {
+    if (stream.destroyed) return;
     stream.push(null);  // pushing null, indicating EOF
   });
 
-  this.on('fields', function(fields, i) {
+  this.on('fields', function on_fields(fields, i) {
+    if (stream.destroyed) return;
     stream.emit('fields', fields, i);  // replicate old emitter
   });
 ```

</details> 

However, this patch may not be sufficient to fix the problem in all situations. I think `resume` should be called in `release` and `end` functions.

This problem is also persistent in `mysql2.`

### PR DESCRIPTION
**Pull request by wellwelwel**
This _PR_ continues #3769 work and fixes #3596. It also seems to resolve #1847 and resolve #1168, ensuring that `destroy` and error events are properly issued (not using _`try-catch`_, but _`stream.on('error', () => {})`_ approach, which is the expected pattern for callbacks).

---

In #3769, it destroys the connection on error to ensure that the stack is not blocked, but this approach can be aggressive, as a query error shouldn't destroy the connection.

In this _PR_, the approach is to destroy the current stream itself on error and emits the appropriate events, ensuring its functionality and allowing users to catch errors that were not previously emitted, as reported in #1847.

---

### Before this _PR_

The test that checks the events is not reached and the script is silently ended prematurely:

Screenshot 2025-08-27 at 05 37 42

### After this _PR_

Now all tests are reached:

Screenshot 2025-08-27 at 05 35 54

---

> [!NOTE]
>
> Thanks @fenichelar, @CarlOlson, and @dsech. Your examples and solutions helped us achieve a better understanding of the error 🤝

### CODE REVIEW

File: lib/commands/query.js [hunk 1]
```diff
@@ -271,33 +271,68 @@ class Query extends Command {
...
+      },
+      destroy: (err, cb) => {
+        this._connection && this._connection.resume();
+
+        /* eslint-disable no-use-before-define */
+        this.removeListener('result', onResult);
+        this.removeListener('fields', onFields);
+        this.removeListener('end', onEnd);
+        this.removeListener('error', onError);
+        /* eslint-enable no-use-before-define */
```
Comment (CarlOlson) [inline lib/commands/query.js:292]: I think this is a valid complaint from `eslint`. These are not `var` and will not be hoisted.

Comment (wellwelwel) [reply lib/commands/query.js:292]: > I think this is a valid complaint from `eslint`. These are not `var` and will not be hoisted.

In this case, if we declare the event methods later, the stream is declared earlier, and vice versa 😂

Regarding the hoist issue, I believe it is not applicable since the `destroy` method will be called after the variables are declared, but a possible approach would be to pass the stream as a parameter to solve this concern.

Comment (wellwelwel) [reply lib/commands/query.js:292]: Even when passing the stream as a parameter, the concept remains the same: the references conflict when declared before or after in the same way. For example:

```js
const onError = (stream) => (err) => {
  stream.destroy(err);
};

const stream = new Readable({
  destroy: (err, cb) => {
    this.removeListener('error', onErrorHandler);
  },
});

const onErrorHandler = onError(stream);

this.on('error', onErrorHandler);
```

Screenshot 2025-08-27 at 07 23 16

Comment (wellwelwel) [reply lib/commands/query.js]: Solved! 🌞✨

I didn't want to overwrite the private stream methods, but it was the most viable and practical alternative.
